config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'terms', to: 'pages#terms', as: :terms
  get "/products/own_products", to: "products#own_products", as: :own_products
  resources :products do
    resources :reviews, only: [:create, :show]
    resources :renting_requests, only: :create
  end
    resources :reviews, only: [:destroy]

  resources :renting_requests, only: [:index, :update]

  # namespace :owner do
  #   resources :renting_requests, only: [:index, :update]
  # end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @review = Review.all
  end

  # def new
  #   @review = Review.new
  # end

  def create
    @review = Review.new(review_params)
    @product = Product.find(params[:product_id])
    @review.user = current_user
    @review.product = @product
    if @review.save
      redirect_to product_path(@product)
    else
      render 'products/show', status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/views/review/_form.html.erb
<%= simple_form_for [@product, review] do |f| %>
  <%= f.input :content %> 
  <%= f.input :rating, collection: (1..5) %> 
  <%= f.submit 'Submit', class:"btn btn-info my-3" %> 
<% end %>

app/views/review/_review.html.erb
<div class="card m-3">
  <div class="card-body">
    <p><% review.rating.times do %>
        <i class="fa-solid fa-star" style="color: #FFD43B;"></i>
      <% end %></p>
    <div class="d-flex justify-content-between">
      <%= review.content %>
    </div>
    <div class="d-flex justify-content-end">
      <%= link_to review_path(review), data: { turbo_method: "delete", turbo_confirm: "Are you sure to delete this review?" }, class:"text-decoration-none" do %>
        <i class="fa-solid fa-trash"></i>
      <% end %>
    </div>
  </div>
</div>