config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'terms', to: 'pages#terms', as: :terms
  get "/products/own_products", to: "products#own_products", as: :own_products
  resources :products do
    resources :reviews, only: [:create, :show]
    resources :renting_requests, only: :create
  end
    resources :reviews, only: [:destroy]

  resources :renting_requests, only: [:index, :update]

  # namespace :owner do
  #   resources :renting_requests, only: [:index, :update]
  # end
end

app/views/shared/_featured.html.erb
<div class="content">
  <h2>Latest Product:</h2>
  <% if @last_product %>
    <div class="card mb-3 mt-3">
      <%= image_tag @last_product.image_url, style: "width: 100%; max-width: 500px;", alt: @last_product.title %>
      <div class="card-body">
        <h2 class="card-title"><%= @last_product.title %></h2>
        <h3>¥<%= @last_product.price %></h3>
        <p>Description: <%= @last_product.description %></p>
        <%= link_to "Show this product", product_path(@last_product), class: "btn btn-outline-info", role: "button" %>
      </div>
    </div>
  <% else %>
    <p>No products available.</p>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <%# fixed-bottom %>
  <div class="container d-flex justify-content-between align-items-center">
    <div class="mb-2 me-4">
      <a href="terms" class="text-decoration-none">Terms of Use</a>
    </div>
    <div class="mb-2 me-4">
      <span>LuxeHaven Global Services Limited </span>
      <span> © 2024 LuxeHaven, Inc.</span>
    </div>
    <div class="mb-2 me-4">
      <span>Japan-日本 | Currency: ¥</span>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-collapse sticky-top" style="font-family:Playfair Display, serif;font-size: 18px">
  <div class="container-fluid position-relative">
    <!-- Title centered in the middle -->
    <h2 class="title position-absolute top-50 start-50 translate-middle">LuxeHaven</h2>
    <!-- Other links on the left -->
    <%= link_to "Home", root_path, class: "navbar-brand d-flex align-items-center position-relative m-2" %>
    <%# <%= link_to "All Articles", products_path, class: "navbar-brand d-flex align-items-center position-relative m-2" %>
    <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa-solid fa-chevron-up fa-rotate-180 text-color: white, text-decoration-none"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <!-- Collapsible button on the right -->
      <ul class="navbar-nav me-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle align-items-center m-2" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <%# ['Jewelries', 'Watches & Bracelets', 'Suits & Dress', 'Sports car & Vintage', 'Boats'] %>
            <li><%= link_to "All Articles", products_path, class: "dropdown-item"  %></li>
            <li><%= link_to "Jewelries", products_path(category: "Jewelries"), class: "dropdown-item" %></li>
            <li><%= link_to "Watches & Bracelets", products_path(category: "Watches & Bracelets"), class: "dropdown-item" %></li>
            <li><%= link_to "Suits & Dresses", products_path(category: "Suits & Dresses"), class: "dropdown-item" %></li>
            <li><%= link_to "Sports car & Vintage", products_path(category: "Sports car & Vintage"), class: "dropdown-item" %></li>
            <li><%= link_to "Boats", products_path(category: "Boats"), class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item dropdown m-2">
          <a class="nav-link" href="#" role="button" id="searchToggle" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa-solid fa-magnifying-glass"></i>
          </a>
          <ul class="dropdown-menu search-bar">
            <%= form_with url: products_path, method: :get, class: "d-flex" do %>
              <%= text_field_tag :query,
                params[:query],
                class: "form",
                placeholder: "Look for an article"
                    %>
              <%= submit_tag "Search", name: "", class:"btn btn-outline-light" %>
            <% end %>
          </ul>
        </li>
        <%= link_to "About", about_path, class: "navbar-brand d-flex align-items-center position-relative m-2" %>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <%= link_to "/renting_requests", class: "d-flex align-items-center position-relative text-color-black text-decoration-none m-2" do %>
            <i class="fa-solid fa-cart-shopping"></i>
            <span class="d-flex align-items-center position-relative m-2">Requests</span>
          <% end %>
          <%= link_to "/products/own_products", class: "d-flex align-items-center position-relative text-color-black text-decoration-none m-2" do %>
            <i class="fa-solid fa-book"></i>
            <span class="d-flex align-items-center position-relative m-2">My Items</span>
            <span class="plus-tooltip">Your Articles</span>
          <% end %>
          <%= link_to "/products/new", class: "d-flex align-items-center position-relative text-color-black text-decoration-none m-2" do %>
            <i class="fa-regular fa-plus nav-icon"></i>
            <span class="plus-tooltip">Add Article</span>
          <% end %>
          <!--avatar dropdown-->
          <li class="nav-item dropdown">
            <a href="#" class="avatar d-flex justify-content-center align-items-center m-2 position-relative"
              id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
              style="background-image: url('<%= current_user.photo.attached? ? cl_image_path(current_user.photo.key) : "" %>')">
              <% unless current_user.photo.attached? %>
                <i class="fa-solid fa-user"></i>
              <% end %>

            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Update profile", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>